import fs from 'fs';
import path from 'path';

export interface RouterRoute {
  method: string;
  routePath: string;
  handlerFile: string;
}

/**
 * Generates a `_router.ts` file that uses `@middy/http-router` to dispatch
 * requests to the correct handler based on method and path.
 *
 * Each handler is lazily imported — only the matched handler loads per invocation.
 *
 * @param outputPath Absolute path where the `_router.ts` file will be written
 * @param routes Array of routes to include in the router
 * @param pathPrefix The path prefix (e.g. `/agents`) prepended to all route paths
 * @returns The handler path string for SST (e.g. `services/agents/api/_router.handler`)
 */
/**
 * Sort routes so that static path segments are matched before parameterized
 * ones. @middy/http-router matches dynamic routes in insertion order, so
 * `/subscriptions/platform/{tenantId}` must come before `/subscriptions/{referenceId}`
 * to avoid the wildcard swallowing the literal "platform" segment.
 */
const sortRoutesBySpecificity = (routes: RouterRoute[], pathPrefix: string): RouterRoute[] => {
  return [...routes].sort((a, b) => {
    const pathA = `${pathPrefix}${a.routePath ? `/${a.routePath}` : ''}` || '/';
    const pathB = `${pathPrefix}${b.routePath ? `/${b.routePath}` : ''}` || '/';
    const segsA = pathA.split('/').filter(Boolean);
    const segsB = pathB.split('/').filter(Boolean);
    const len = Math.max(segsA.length, segsB.length);
    for (let i = 0; i < len; i++) {
      const sa = segsA[i] ?? '';
      const sb = segsB[i] ?? '';
      const isDynA = sa.startsWith('{');
      const isDynB = sb.startsWith('{');
      if (!isDynA && isDynB) return -1;
      if (isDynA && !isDynB) return 1;
      if (sa !== sb) return sa.localeCompare(sb);
    }
    return segsB.length - segsA.length;
  });
};

export const generateRouterFile = (
  outputPath: string,
  routes: RouterRoute[],
  pathPrefix: string,
): string => {
  const sortedRoutes = sortRoutesBySpecificity(routes, pathPrefix);
  const routeEntries = sortedRoutes.map(({ method, routePath, handlerFile }) => {
    // Build the full path including prefix
    const fullPath = `${pathPrefix}${routePath ? `/${routePath}` : ''}` || '/';

    // Build relative import path from the router file to the handler
    const routerDir = path.dirname(outputPath);
    let relativePath = path.relative(routerDir, handlerFile).replace(/\.ts$/, '.js');
    if (!relativePath.startsWith('.')) {
      relativePath = `./${relativePath}`;
    }

    return `  {
    method: '${method.toUpperCase()}' as const,
    path: '${fullPath}',
    handler: async (event: any, context: any, abort: any) =>
      (await import('${relativePath}')).handler(event, context, abort),
  }`;
  });

  const content = `// Auto-generated by @auriclabs/sst-utils — do not edit
import middy from '@middy/core';
import httpRouterHandler from '@middy/http-router';

const routes = [
${routeEntries.join(',\n')},
];

export const handler = middy().handler(httpRouterHandler(routes));
`;

  fs.writeFileSync(outputPath, content, 'utf-8');

  return outputPath.replace(/\.ts$/, '.handler');
};
