import fs from 'fs';
import path from 'path';

const MIGRATION_FILE_REGEX = /^(\d{14})_(.+)\.(ts|js)$/;

/**
 * Convert a dash-separated name to a camelCase identifier.
 * e.g. "update-user-roles" → "updateUserRoles"
 */
function toCamelCase(name: string): string {
  return name.replace(/-([a-z0-9])/g, (_, char: string) => char.toUpperCase());
}

/**
 * Scan a migrations directory and write an `index.ts` that imports all migration
 * files and exports a `migrations` const via `defineMigrations()`.
 *
 * @returns The path of the generated index file.
 */
export function generateMigrationIndex(dir: string): string {
  const resolvedDir = path.resolve(dir);

  if (!fs.existsSync(resolvedDir)) {
    throw new Error(`Migrations directory does not exist: ${resolvedDir}`);
  }

  const files = fs
    .readdirSync(resolvedDir)
    .filter((f) => MIGRATION_FILE_REGEX.test(f))
    .sort();

  const usedIdentifiers = new Set<string>();
  const entries: { stem: string; identifier: string }[] = [];

  for (const file of files) {
    const match = MIGRATION_FILE_REGEX.exec(file);
    if (!match) continue;
    const stem = `${match[1]}_${match[2]}`;
    let identifier = toCamelCase(match[2]);

    if (usedIdentifiers.has(identifier)) {
      let suffix = 2;
      while (usedIdentifiers.has(`${identifier}${suffix}`)) suffix++;
      identifier = `${identifier}${suffix}`;
    }

    usedIdentifiers.add(identifier);
    entries.push({ stem, identifier });
  }

  const imports = entries.map((e) => `import ${e.identifier} from './${e.stem}';`).join('\n');

  const migrationEntries = entries.map((e) => `  '${e.stem}': ${e.identifier},`).join('\n');

  const content = [
    '// This file is auto-generated by auric-migrate. Do not edit manually.',
    '// Regenerate with: auric-migrate generate -d <directory>',
    "import { defineMigrations } from '@auriclabs/migrations';",
    '',
    imports,
    '',
    `export const migrations = defineMigrations({`,
    migrationEntries,
    '});',
    '',
  ].join('\n');

  const indexPath = path.join(resolvedDir, 'index.ts');
  fs.writeFileSync(indexPath, content, 'utf-8');

  return indexPath;
}
